### ISSUE TITLE
"undefined local variable or method `root_url'" in version 0.9

### ISSUE THREAD

**Issue by bbauer** [rails-api/active_model_serializers#734]
After upgrading from 0.8.2 to 0.9 I can no longer use root_url in my serializers. Trying to do something like...

``` Ruby
File.join(root_url, object.preview_url)
```

results in "undefined local variable or method `root_url'"
