### ISSUE TITLE
Inherited methods are hidden in serializer

### ISSUE THREAD

**Issue by dpogue** [rails-api/active_model_serializers#1653]
#### Expected behavior vs actual behavior
When subclassing a serializer, the parent class's instance methods are not populated in the child class's instance method list, so `_serializer_instance_method_defined?` returns false.

This started breaking with commit a065bc28d1739631c6177c2995ba345ebcb0c7c8.

#### Steps to reproduce
```ruby
class ParentSerializer < ActiveModel::Serializer
  attributes :$id

  define_method(:$id) do
    object.id
  end
end
```

```ruby
class ChildSerializer < ParentSerializer
  attributes :name
end
```

Throws the following error:
`undefined method '$id' for <Child:0x00...>`

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*:  7acbb765bdbf0a6ad8d5bde02aa3648b2b4a48ea

Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

OS Type & Version: OSX 10.11.4

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails

**Comment by bf4** [comment]
Oh interesting.  

I can fix that, unless you're interested in helping out with a pr.

Also, curious, what are you using the define_method for?  Could use an attribute with the key: option or just alias the id method

**Comment by dpogue** [comment]
In practice, I'm using URIs for identifiers, so `define_method(:$id)` returns `scope.url_for(self)`. Ruby won't let you use `def` for a method starting with a $.

**Comment by bf4** [comment]
Should be fixed by https://github.com/rails-api/active_model_serializers/pull/1661
