### ISSUE TITLE
0.8.x NoMethodError (undefined method `object' for )

### ISSUE THREAD

**Issue by OpakAlex** [rails-api/active_model_serializers#856]
This happens when i try load has_many with include true, and embed: :ids

**Comment by JoshSmith** [comment]
Can you provide a full example? Thanks @OpakAlex!

**Comment by OpakAlex** [comment]
it works on 0.9.3
