### ISSUE TITLE
Test against  `ActionController::API`

### ISSUE THREAD

**Issue by bf4** [rails-api/active_model_serializers#1634]
Currently AMS tests only against `ActionController::Base`.

`rails-api` has been merged into Rails 5 so that it will have `ActionController::API`, which would be the recommended controller base class to use with AMS.

- [ ] Add `rails-api` gem to Gemfile for rails version < 5
- [ ] Add tests against `ActionController::API`
- [ ] Change tests ApplicationController to use ActionController::API, rather than ActionController::Base for most cases.

**Comment by ncuesta** [comment]
*I was about to post an issue related to this, but I think it may be better to add some info to this topic.*

We've just run into an issue introduced by d5833e8e. When we hit any of our controllers on a Rails 5.0.0.beta3 application in `--api` mode, we get this error:

```
ActionController::RoutingError (undefined local variable or method `cache_store' for ActionController::API:Class):

app/controllers/application_controller.rb:1:in `<top (required)>'
app/controllers/requests_controller.rb:1:in `<top (required)>'
```

It seems that the offending part is due to [this change](https://github.com/rails-api/active_model_serializers/commit/d5833e8e1b51668042495dd236a9503f56b868c6#diff-ea54b1890c9c0946dbe2bf6bd5e8c1d8R31), and that may have not rang any bell because the gem isn't being tested against `ActionController::API`, a trimmed version of `ActionController::Base`.

If I may vote, this issue is a big :+1:

Besides that, I wanted to thank you guys for the great job being done in this gem.

**Comment by bf4** [comment]
@ncuesta Thanks.  So, it appears I'm correct that it's safer to run mixin code in the `on_load` hook so I don't need to worry if it's `::Base` or `::API`, but I still need to make sure there's e.g. `cache_store` on both.  In this case, fix would be just to specify

```diff
-        ActiveModelSerializers.config.cache_store = cache_store
+        ActiveModelSerializers.config.cache_store = ActionController::Base.cache_store
```

would you mind making a PR and mark it as a bug and link here?
