### PR TITLE
Fix `#as_json` glitch caused by JSON and Rails

### PR DESCRIPTION
**Pull request by mhuggins**
This addresses issue #340 for the 0.8.x series.  It looks like the existing fix for that issue was not included in that series of active_model_serializers.

### CODE REVIEW

File: lib/active_model/serializer.rb [hunk 1]
```diff
@@ -338,7 +338,7 @@ def to_json(*args)
     # object including the root.
     def as_json(options={})
       options ||= {}
-      if root = options.fetch(:root, @options.fetch(:root, root_name))
+      if root = options.to_hash.fetch(:root, @options.fetch(:root, root_name))
```
Comment (bf4) [inline lib/active_model/serializer.rb]: failing test?

Comment (mhuggins) [inline lib/active_model/serializer.rb]: I'll check it out tomorrow.

Comment (mhuggins) [inline lib/active_model/serializer.rb]: Interesting, these tests are already failing on 0.8.3 prior to this change.

Comment (mhuggins) [inline lib/active_model/serializer.rb]: For reference: https://travis-ci.org/rails-api/active_model_serializers/builds/43605004

Comment (mhuggins) [inline lib/active_model/serializer.rb]: It looks like the 0-8-stable branch has been failing since 2013, looks like this PR broke it: https://github.com/rails-api/active_model_serializers/pull/477

Comment (mhuggins) [inline lib/active_model/serializer.rb]: @bf4 I fixed some of your gem's tests, so this is now in a better state than the current 0-8-stable branch.  It's not passing on some older versions of ruby that you guys are testing on travis because:

> mime-types requires Ruby version >= 1.9.2

[as seen here](https://travis-ci.org/rails-api/active_model_serializers/builds/89587378).

Comment (bf4) [inline lib/active_model/serializer.rb]: @mhuggins s/my/our gem.  Thanks for looking into this.  Sorry for being slow here...

Comment (mhuggins) [inline lib/active_model/serializer.rb]: No problem, hopefully this is helpful and looks good. :)

**Comment by beauby** [comment]
Somebody familiar with the 0.8 codebase to review this? cc @joaomdmoura

**Comment by mhuggins** [comment]
Just thought I'd follow up to see if there's anything else I can offer here.

**Comment by beauby** [comment]
Considering ruby 1.8.7 has been EOLed a few years ago, and considering changes necessitating ruby >= 1.9.3 have been committed to the 0.8 branch, I believe we can safely remove support for ruby < 1.9.3, and merge this commit.
What I suggest is to add a commit that changes the `.travis.yml` to this PR, so that it also removes old rubies tests, and then keep on rocking.

**Comment by beauby** [comment]
Also, thanks a lot @mhuggins for taking the time to make this PR happen, and for following up!

**Comment by mhuggins** [comment]
Cool, happy to do that.  I've got some work critical stuff this week, but I'll plan on updating this week.  I appreciate you getting back to me! :)

**Comment by mhuggins** [comment]
@beauby I've updated the `.travis.yml` file, and tests are now passing.  In addition to removing 1.8.7 and 1.9.2, I had to remove ree for the same reason since it's built upon the 1.8 series.

Let me know if there's anything else that needs to be addressed.  Thanks! :smile:

File: test/serialization_test.rb [hunk 2]
```diff
@@ -242,7 +242,7 @@ def test_render_json_with_status
 
   def test_render_json_with_callback
     get :render_json_hello_world_with_callback
-    assert_equal 'alert({"hello":"world"})', @response.body
+    assert_equal '/**/alert({"hello":"world"})', @response.body
```
Comment (bf4) [inline test/serialization_test.rb]: oh weird, shouldn't it have been this the whole time?

File: test/serializer_test.rb [hunk 3]
```diff
@@ -1363,6 +1363,7 @@ def name
   def test_inheritance_does_not_used_cached_attributes
     parent = Class.new(ActiveModel::Serializer) do
       attributes :title
+      alias :read_attribute_for_serialization :send
```
Comment (bf4) [inline test/serializer_test.rb]: This is needed? If so, it probably shouldn't just be in the test, but generally in the serializer, no?

Also, see https://github.com/rails/rails/blob/4-2-stable/activemodel/lib/active_model/serialization.rb#L141

File: test/serialization_test.rb (hunk 2 above)
Comment (mhuggins) [inline test/serialization_test.rb]: Yep, it is currently failing on the 0.8 branch.  This fixes it.

**Comment by bf4** [comment]
Seems like you'll need to add an [`appveyor.yml`](https://github.com/rails-api/active_model_serializers/blob/f562449bd439d1295b91b41b01d5b780c793100a/appveyor.yml) to get Travis to go green

File: test/serializer_test.rb (hunk 3 above)
Comment (mhuggins) [inline test/serializer_test.rb]: Good callout.  Happy to change it if this is the desired fix.

**Comment by mhuggins** [comment]
I've never used appveyor.  The 0.8 branch was failing historically, so nothing new broke here.  Any insight into what I can do to get that working?

**Comment by bf4** [comment]
@mhuggins I think the big problems with CI on the 0-8-branch were related to incompatibilities with Rails < 4, and the lack of a Rails version constraint in CI.

I've addressed those in https://github.com/rails-api/active_model_serializers/pull/1376 basically copying what we have in master.  Hopefully, that should let you focus on the bug your fixing.

I included all your CI-specific commits in #1376

**Comment by mhuggins** [comment]
Cool, I think it's safe to close this PR in favor of that one then. Thanks!!

**Comment by bf4** [comment]
Oh, but I left out  2dbc4ddbaeb00388068843a9aecf00356b11abf7

Do you think it's no longer needed?

**Comment by bf4** [comment]
Do you think it's worth working on the ruby < 1.9.3, rails < 4.0 test support?

**Comment by bf4** [comment]
In the referenced bug you wrote

> I'm still seeing this error on Rails 3.2.22 with ActiveModel Serializers 0.8.3. Am I missing something?

    ```ruby
    serializer = Service::Notifications::NewsroomSerializer.new(newsroom)
    s = serializer.to_json
    # => "{\"name\":\"Huggie\",\"subdomain\":\"huggie\"}" 

    JSON.dump(s)
    # => NoMethodError: undefined method `fetch' for #<JSON::Ext::Generator::State:0x007faf44dc3048>

    MultiJson.dump(s)
    # => "{\"name\":\"Huggie\",\"subdomain\":\"huggie\"}" 
    ```

Which I haven't confirmed if it's still a problem

**Comment by mhuggins** [comment]
Ahh, okay, I misunderstood.  I'll reopen a new PR with just that change then, if that works for you. :)

**Comment by bf4** [comment]
No need, you can just force push to this branch

**Comment by mhuggins** [comment]
:+1: Will do shortly

**Comment by mhuggins** [comment]
Sorry for the delay, I'm going to make sure to address this during the week.
