### ISSUE TITLE
undefined method `associations' for #<ActiveModel::Serializer::CollectionSerializer`

### ISSUE THREAD

**Issue by Startouf** [rails-api/active_model_serializers#2105]
I have an API that sends custom data aggregated with the MongoDB driver. The aggregations are just put into an array, and the controller performs `format.json { render json: [@aggregated, @datas] }`

#### Expected behavior vs actual behavior
I was expecting the Controller to skip any particular serialization, and just deliver the JSON data with the raw values. This is what happens in development

However, in production environment, I am faced with 

> undefined method `associations' for #<ActiveModel::Serializer::CollectionSerializer:

#### Steps to reproduce
Here's how my code looks like
```
class MyAPIController < SomeAPIController
  def show
    @empl_data = employee_list
    @aggregated = employee_aggregation

    respond_to do |format|
      format.html
      format.json { render json: [@aggregated, @empl_data] }
      format.csv  { render csv: [@aggregated, @empl_data] }
    end
  end

  private

  # Return aggregation of datas for whole company
  def employee_aggregation
    agg = nil

    if @empl_data
      agg = @empl_data.transpose
      agg = agg.drop(3) # Delete user data
      agg.delete_at(2) # Delete other irrelevant data

      # Abort if there are no employees
      return [] if agg.empty?

      agg[0] = agg[0].count { |x| x == true } 
      ...
      agg[8] = agg[8].reduce(:+) / (agg[8].size.nonzero? || 1) # recommendation_rate
    end
    [agg]
  end

  # Return list of employee with aggregated stats
  def employee_list
    datas = []
    @company.employees.each do | employee |
      datas.push([
        employee._id.to_s,
        employee.name,
        metric_service.some_aggregation1_for(employee),
       ....
        metric_service.some_aggregationx_for(employee)
      ])
    end
    return datas
  end

  def metric_service
    @metric_service ||= MyAggregationService.new
  end
```
There is no serializer associated (And I don't want to use a particular serialization, all the data is ready to be used by the frontend)

#### Environment
I tried to update AMS to the latest version so `active_model_serializers 0.10.5 (was 0.10.2)` but both versions are crashing
Ruby -- 2.3.4p301
OS Ubuntu 14
Rails 5.0.2

#### Backtrace
For some reason I don't have the full framework trace and until I can show it fully here is just the start of the trace I received via Exception Notifier
```
An exception occurred: 'undefined method `associations' for #<ActiveModel::Serializer::CollectionSerializer:0x00000009a55740>' on '/var/www/myapp/shared/bundle/ruby/2.3.0/gems/active_model_serializers-0.10.2/lib/active_model/serializer/caching.rb:182:in`
```

**Comment by bf4** [comment]
`@datas` isn't defined anywhere. Is that a typo in the code or example?

The code was working in 0.10.2 but broke in 0.10.5?

Could you share your serializer code?  Based on the stacktrace that you shared https://github.com/rails-api/active_model_serializers/blob/v0.10.2/lib/active_model/serializer/caching.rb#L182  your serializer doesn't implements associations for some reason

**Comment by Startouf** [comment]
Sorry, `@data` was a typo, had renamed to `@empl_data` for the example.

No the code os not working for both versions

Sorry if it wasn't clear, I don't want to use a serializer for this particular controller, so I have no serializer code to share. For some reason the app seems call a `ActiveModel::Serializer::CollectionSerializer` but there all the data variables are raw values (strings/floats) and there is no model object in the `[@aggregated, @empl_data]` (so I was expecting a default rendering).

I realised just this morning I wasn't always observing the crash, so it's data dependent. I will go back to you as soon as I have examples of crashing data.

**Comment by Startouf** [comment]
@bf4 I have several cases of errors but one happens when I try to serialize an array of empty arrays

```
empty_arrays =  [ [], [] ]
respond_to do |format|
  format.json { render json: empty_arrays }
end
```

Is there a way I can maybe specify a serializer via `serializer` or `each_serializer` to avoid the crashes ? 

Here is the backtrace
```
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model/serializer/concerns/caching.rb:182:in `block in object_cache_keys'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model/serializer/collection_serializer.rb:5:in `each'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model/serializer/collection_serializer.rb:5:in `each'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model/serializer/concerns/caching.rb:179:in `object_cache_keys'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model/serializer/concerns/caching.rb:164:in `cache_read_multi'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model/serializer/collection_serializer.rb:23:in `serializable_hash'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/adapter/attributes.rb:7:in `serializable_hash'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/adapter/base.rb:59:in `as_json'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/json/encoding.rb:33:in `encode'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/json/encoding.rb:20:in `encode'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/core_ext/object/json.rb:37:in `to_json'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/serializable_resource.rb:8:in `to_json'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:69:in `block (3 levels) in notify'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:126:in `call'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:22:in `block (3 levels) in instrument_rendering'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:79:in `block in notify_render'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/notifications.rb:164:in `instrument'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:78:in `notify_render'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:21:in `block (2 levels) in instrument_rendering'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:95:in `block in tag_logger'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:95:in `tag_logger'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:391:in `instance_exec'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:285:in `block in halting'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:447:in `block in around'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:455:in `call'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:750:in `_run_render_callbacks'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/renderers.rb:157:in `block in <module:Renderers>'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/active_model_serializers-0.10.5/lib/action_controller/serialization.rb:62:in `block (2 levels) in <module:Serialization>'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/renderers.rb:150:in `block in _render_to_body_with_renderer'
/Users/Cyril/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/set.rb:306:in `each_key'
/Users/Cyril/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/set.rb:306:in `each'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/renderers.rb:146:in `_render_to_body_with_renderer'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/abstract_controller/rendering.rb:26:in `render'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/rendering.rb:36:in `render'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/Cyril/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/activesupport-5.0.2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/elasticsearch-rails-0.1.9/lib/elasticsearch/rails/instrumentation/controller_runtime.rb:20:in `cleanup_view_runtime'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.2/lib/action_controller/metal/instrumentation.rb:43:in `render'
/Users/Cyril/.rvm/gems/ruby-2.3.3/gems/meta-tags-2.3.1/lib/meta_tags/controller_helper.rb:20:in `render'
/Users/Cyril/dev/myapp/app/controllers/my_crashing_controller.rb:19:in `block (2 levels) in show'
```

**Comment by bf4** [comment]
If you're trying to `render json:  [ [], [] ]`, AMS will see the collection and try to find the serializer for each item in the collection.  Then, it will see each item is a collection, and fail under the assumption it can figure out what type of object you're serializing.

Easiest thing to do in this case: `render json:  [ [], [] ].to_json`.  AMS will ignore the payload when it's a string.

**Comment by bf4** [comment]
Closing as stale and resolved. Please feel free to continue discussing.
