### ISSUE TITLE
New fieldset params causes passing root as symbol to fail

### ISSUE THREAD

**Issue by FeminismIsAwesome** [rails-api/active_model_serializers#2342]
#### Expected behavior vs actual behavior

Prior to v0.10.10, passing a symbol key to :root resolved. I think this is due to a change moved in from 0.10.9.

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

```
def show
render json: serialized_data, :each_serializer => MySerializer, root: :my_root
end
```
will blow up, vs

```
def show
render json: serialized_data, :each_serializer => MySerializer, root: 'my_root'
end
```
Resolves correctly.
#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
OS Type & Version: 
Mac OS X, 10.14.4 mojave
Integrated application and version *(e.g., Rails, Grape, etc)*: 
Rails 5

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

```
 undefined method `singularize' for :package_types:Symbol
     # ./app/controllers/admin/package_types_controller.rb:8:in `block (2 levels) in index'
     # ./app/controllers/admin/package_types_controller.rb:5:in `index'
     # ./spec/controllers/admin/package_types_controller_spec.rb:20:in `block (5 levels) in <top (required)>'
```

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

I believe that the addition of https://github.com/rails-api/active_model_serializers/pull/2223/files caused this to start happening, as the addition of the fieldset seems likely origin of ` undefined method `singularize' for :package_types:Symbol`. If that's an error that's intended/symbol usage bad, that would've been nice to see in the docs/changelog, and i'd be happy to submit a PR for that.

**Comment by wasifhossain** [comment]
going to address this on the other issue. thanks
