### ISSUE TITLE
Array render not working anymore on 4.2.0

### ISSUE THREAD

**Issue by solher** [rails-api/active_model_serializers#772]
Hi,

I just noticed that my error messages are not rendered anymore since 4.2.0 (and AMS master, otherwise, serializers are never reached with 0.9).

I've got a :
"NoMethodError (undefined method `new' for nil:NilClass)"

when I try to do :
"render json: [ 'No session found for the current user' ]"

It seems to be looking for a serializer for the object but it finds nothing since an array isn't a "custom" class.
Maybe it is just because what I'm doing is bad practice, I don't know...
Thanks for the help !

**Comment by kurko** [comment]
It shouldn't fail like this. Will take a look later. It's bug and needs to be fixed. If you want to make it work right now, I'd suggest having something more descriptive. Have you checked http://jsonapi.org? Their error format would work fine with AMS.

**Comment by ryansch** [comment]
I just hit my head on this in our default error handling for the api.  The problem here is trying to render out any type that doesn't have a corresponding Serializer inside of an array.

Normal flow:
We'll try `render json: 'a string'`.  AMS fails to find a serializer for the string literal and the action controller extension bails out on https://github.com/rails-api/active_model_serializers/blob/master/lib/action_controller/serialization.rb#L41 and uses rails' built in render.

Error'd flow:
We'll try to `render json: ['a string']`.  This time AMS is able to find an ArraySerializer for the array but then fails to find the serializer class in https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model/serializer/array_serializer.rb#L13-L17 and raises the error reported in this issue.

AMS should be able to catch this error and fall back to the default render.

**Comment by ryansch** [comment]
To be clear: We usually return something like `{ errors: ['some error'] }`.  I discovered this behavior due to a bug in one of our controllers.

**Comment by nessur** [comment]
This version of AMS lacks any support for a 'default' serializer, which in 0.9.0 allowed any rendering of a ruby class that responds to 'as_json'. So, AMS 0.10.0.rc1 can't serialize: String, Hash, Time, Integer

from Pry, in our rspec test suite:
```
from: /Users/me/.rvm/gems/ruby-2.1.1/gems/active_model_serializers-0.10.0.rc1/lib/active_model/serializer/array_serializer.rb @ line 17 ActiveModel::Serializer::ArraySerializer#initialize:

     9: def initialize(objects, options = {})
    10:   options.merge!(root: nil)
    11:
    12:   @objects = objects.map do |object|
    13:     serializer_class = options.fetch(
    14:       :serializer,
    15:       ActiveModel::Serializer.serializer_for(object)
    16:     )
 => 17:     binding.pry unless serializer_class
    18:     serializer_class.new(object, options)
    19:   end
    20:   @meta     = options[:meta]
    21:   @meta_key = options[:meta_key]
    22: end

[1] pry(#<ActiveModel::Serializer::ArraySerializer>)> ActiveModel::Serializer.serializer_for(1)
=> nil
[2] pry(#<ActiveModel::Serializer::ArraySerializer>)> ActiveModel::Serializer.serializer_for('hey')
=> nil
[3] pry(#<ActiveModel::Serializer::ArraySerializer>)> ActiveModel::Serializer.serializer_for(Time.now)
=> nil
[4] pry(#<ActiveModel::Serializer::ArraySerializer>)> ActiveModel::Serializer.serializer_for({})
=> nil
[5] pry(#<ActiveModel::Serializer::ArraySerializer>)> ActiveModel::Serializer.serializer_for([])
=> ActiveModel::Serializer::ArraySerializer
```

**Comment by GriffinHeart** [comment]
Got bitten by this, its specially bad when trying to migrate from an existing API to use AMS if it keeps this behaviour it means we can't migrate in steps (one serialiser at a time) and have to do it for everything.

In the end I did a find and replace to every `render` and put a `.to_json` on everything that didn't use AMS.

**Comment by bf4** [comment]
I believe this was fixed in https://github.com/rails-api/active_model_serializers/issues/772 for raw json in associations, and `render json: [ 'No session found for the current user' ]` will skip using AMS serializers altogether

**Comment by beauby** [comment]
Closing this as it seems to be fixed in master. Feel free to reopen if neede.
